name: Publish Python Package to PyPI

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/ak-gpapi/
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
        cache: pip
    - name: Install dependencies
      run: |
        pip install setuptools wheel build
    - name: Build
      run: |
        python setup.py build
    - name: Publish
      uses: pypa/gh-action-pypi-publish@release/v1